sergelogvinov/proxmox-csi-plugin

- .conform.yaml
- .github/workflows/build-edge.yaml
- .github/workflows/build-test.yaml
- .github/workflows/charts.yaml
- .github/workflows/conform.yaml
- .github/workflows/release.yaml
- .golangci.yml
- Makefile
- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- cmd/node/main.go
- hack/ct.yml
- pkg/csi/controller.go
- pkg/csi/identity.go
- pkg/csi/node.go
- pkg/csi/utils.go
- pkg/volume/volume.go
> ci: github actions

- .github/workflows/release-pre.yaml
- Makefile
- charts/proxmox-csi-plugin/Chart.yaml
- hack/CHANGELOG.tpl.md
- hack/chglog-config.yml
> ci: check release

- CHANGELOG.md
- hack/CHANGELOG.tpl.md
- hack/chglog-config.yml
> chore: release v0.0.1

- CHANGELOG.md
- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
- docs/release.md
Release 0.0.2, helm chart fix.
> chore: release v0.0.2

- .conform.yaml
- Makefile
- README.md
- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- charts/proxmox-csi-plugin/README.md.gotmpl
- charts/proxmox-csi-plugin/values.yaml
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
Update helm charts values descriprions.
> docs: helm readme

- Dockerfile
- README.md
- docs/deploy/test-pod-ephemeral.yaml
- docs/deploy/test-statefulset.yaml
- tools/deps.sh
Copy only required filesystem tools.
> feat: decrease node image

- .github/workflows/build-edge.yaml
- .github/workflows/build-test.yaml
- Dockerfile
- Makefile
- tools/deps-check.sh
- tools/deps.sh
* add trivy image test
* linux dependency test
> ci: test images

- Dockerfile
Use distroless image in node side plugin.
No bash, no perl...
> feat: switch to distroless

- CHANGELOG.md
- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
> chore: release v0.1.1

- .github/workflows/build-test.yaml
- go.mod
- go.sum
- pkg/csi/controller.go
Fix detachVolume error message (nil pointer dereference).
> fix: detach volume error

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/workflows/build-edge.yaml
- .github/workflows/build-test.yaml
- .github/workflows/release.yaml
Registry sometimes has push issue.
Set build/push limit.
> cicd: build timeout

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- charts/proxmox-csi-plugin/templates/controller-deployment.yaml
- charts/proxmox-csi-plugin/templates/node-deployment.yaml
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
Miss securityContext for liveness-probe.
> fix: helm liveness context

- .golangci.yml
- Dockerfile
- pkg/csi/node.go
- tools/deps-check.sh
- tools/deps.sh
We will send trim command during unmount process.
> feat: trim filesystem

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- charts/proxmox-csi-plugin/templates/node-deployment.yaml
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
Set only SYS_ADMIN, CHOWN, DAC_OVERRIDE.
Last two use fsGroupChangePolicy (future plans).
> feat: drop node capabilities

- .dockerignore
- .github/workflows/release-charts.yaml
- .gitignore
- Makefile
- README.md
- docs/release.md
> feat: helm oci release

- .dockerignore
- .github/dependabot.yml
- .github/workflows/build-edge.yaml
- .github/workflows/build-test.yaml
- .github/workflows/charts.yaml
- .github/workflows/conform.yaml
- .github/workflows/release-pre.yaml
- .github/workflows/release.yaml
- .gitignore
- Makefile
- docs/cosign.md
- docs/release.md
It helps to check that images were build in github-actions.
> feat: cosign images

- CHANGELOG.md
- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
> chore: release v0.2.0

- Dockerfile
- docs/benchmark.md
- docs/deploy/test-statefulset.yaml
- tools/deps-check.sh
- tools/deps.sh
Update deps.
Backmerge deps.sh from openstack project.
> chore: bump deps

- pkg/csi/controller.go
- pkg/csi/controller_test.go
- pkg/csi/node.go
Add SINGLE_NODE_MULTI_WRITER capability.
It does not change anything, just will support new kubernetes behavior.
> feat: volume capability

- README.md
- docs/benchmark.md
- docs/deploy/debug.yaml
- docs/options.md
> docs: storage class options

- CHANGELOG.md
- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- charts/proxmox-csi-plugin/templates/controller-deployment.yaml
- charts/proxmox-csi-plugin/templates/node-deployment.yaml
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
> chore: release v0.3.0

- Dockerfile
- README.md
- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/templates/csidriver.yaml
- charts/proxmox-csi-plugin/values.yaml
- docker-compose.yml
- docs/options.md
- go.mod
- go.sum
- pkg/csi/controller.go
- pkg/csi/driver.go
Proxmox has a disk speed limit.
We can pass these parameters during the mount process. This will help us understand how the application will perform in well-known cloud environments.
> feat: disk speed limit

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/templates/csidriver.yaml
- docs/deploy/test-statefulset.yaml
- docs/options.md
- docs/proxmox-lvm.yaml
- pkg/csi/controller.go
- pkg/csi/controller_test.go
- pkg/csi/driver.go
- pkg/csi/node.go
Add CSI blockSize/inodeSize format options.
close #62
> feat: mkfs block/inode size options

- cmd/controller/main.go
- cmd/node/main.go
- pkg/csi/controller.go
- pkg/csi/controller_test.go
- pkg/csi/node.go
- pkg/csi/node_test.go
- pkg/csi/utils.go
CreateVolume can get timeout error from Proxmox.
Proxmox sometimes need more time to create volume disk. We need to check equal volume existence.
close #98 
> fix: check volume existence

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
It helps the community to conduct their own investigation before creating an issue
> ci: update bug template

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- charts/proxmox-csi-plugin/templates/node-deployment.yaml
- charts/proxmox-csi-plugin/values.yaml
- docs/deploy/proxmox-csi-plugin-release.yml
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
Add location of the /var/lib/kubelet directory as some k8s distribution differ from the standard.
> feat(chart): add value to customize kubeletDir

- CHANGELOG.md
- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- docs/deploy/proxmox-csi-plugin-release.yml
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
- docs/options.md
> chore: release v0.4.1

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- charts/proxmox-csi-plugin/templates/csidriver.yaml
- charts/proxmox-csi-plugin/templates/node-deployment.yaml
- charts/proxmox-csi-plugin/values.yaml
- docs/deploy/proxmox-csi-plugin-release.yml
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
Update daemonset security context.
> feat: use readonly root

- .goreleaser.yml
- Dockerfile
- Makefile
- cmd/pvecsi-mutate/main.go
- cmd/pvecsi-mutate/migrate.go
- cmd/pvecsi-mutate/rename.go
- cmd/pvecsi-mutate/utils.go
- go.mod
- go.sum
- pkg/csi/driver.go
- pkg/log/log.go
- pkg/proxmox/volume.go
- pkg/tools/config.go
- pkg/tools/nodes.go
- pkg/tools/pv.go
CLI tool to move disk between proxmox node.
To maintain or remove node from cluster and save the data.
> feat: pv/pvc cli helper

- cmd/controller/main.go
- cmd/node/main.go
- go.mod
- go.sum
- pkg/csi/driver.go
- pkg/csi/node.go
- tools/deps.sh
We will wait 3 seconds before return success.
also close #59
> fix: add delay before unattach device

- docs/pvecsictl.md
> docs: cli tool example

- .github/workflows/release.yaml
- .goreleaser.yml
> fix: goreleaser

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- charts/proxmox-csi-plugin/templates/_storage.tpl
- charts/proxmox-csi-plugin/templates/controller-deployment.yaml
- charts/proxmox-csi-plugin/templates/storageclass.yaml
- charts/proxmox-csi-plugin/values.yaml
- docs/deploy/proxmox-csi-plugin-release.yml
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
* refactoring storageClass
* add initContainers and hostAliases
It helps to use sidecar loadbalancer on top of proxmox.
> feat(chart): add initContainers and hostAliases

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/templates/storageclass.yaml
Add support for setting annotations and labels on storage classes
Setting annotations on storage classes is required in order to be able to designate them as the default storage class.
- [n/a] you linked an issue (if applicable)
- [n/a] you included tests (if applicable)
- [n/a] you linted your code (`make lint`)
- [n/a] you linted your code (`make unit`)
> Support setting annotations and labels on storageClasses

- cmd/pvecsictl/migrate.go
- cmd/pvecsictl/utils.go
- pkg/proxmox/volume.go
Use current size dyring creating.
> fix: cli migration

- .github/workflows/build-test.yaml
- .github/workflows/release.yaml
- Dockerfile
> fix: deps update

- cmd/pvecsictl/utils.go
- pkg/tools/pv.go
It addresses the migration issue that occurs when the PVC size has been changed.
> fix: pvc migration

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/values.yaml
- docs/deploy/proxmox-csi-plugin-release.yml
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
> chore(chart): update sidecar deps

- .github/workflows/release.yaml
- docs/release.md
Fix release proccess doc.
release-please requirese more permission to run builds.
> fix: release doc

- .github/workflows/release.yaml
Prepare qemu images to run buildx
> fix: build release

- pkg/tools/pv.go
Fix check POD status.
Pod pending is a normal pod status in force mode.
> fix: pv force migration

- .github/workflows/build-test.yaml
- .github/workflows/release.yaml
- .golangci.yml
- docker-compose.yml
- pkg/csi/controller.go
- pkg/csi/controller_test.go
- pkg/csi/identity_test.go
- pkg/csi/node.go
- pkg/csi/node_test.go
- pkg/csi/utils.go
- pkg/volume/volume.go
Shared volumeIDs are now independent of the nodes they are created on.
https://github.com/sergelogvinov/proxmox-csi-plugin/issues/185
> refactor: improve support for shared block devices

- pkg/csi/node.go
> fix: implement structured logging

- .github/workflows/stale.yaml
> ci: add stale issues

- pkg/csi/utils.go
Proxmox delays the volume detach operation sometimes. This commit adds a wait loop to wait for the volume to be detached.
> feat: wait volume to be detached

- README.md
- docs/pvecsictl.md
> docs: update readme

- ADOPTERS.md
> docs: add adopters list

- README.md
> Update README.md typo fixed

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- charts/proxmox-csi-plugin/templates/controller-deployment.yaml
- charts/proxmox-csi-plugin/values.yaml
- docs/deploy/proxmox-csi-plugin-release.yml
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
- docs/metrics.md
Add controller podAnnotations for metric discovery.
> fix: helm chart podAnnotation

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- charts/proxmox-csi-plugin/templates/controller-deployment.yaml
- docs/deploy/proxmox-csi-plugin-release.yml
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
Revert metrics-address flag.
We need to change minor version of chart on release process.
close #239
> revert: chart metrics

- .github/workflows/build-edge.yaml
- .github/workflows/release-charts.yaml
- .github/workflows/release.yaml
- Dockerfile
- cmd/pvecsictl/migrate.go
- cmd/pvecsictl/rename.go
- cmd/pvecsictl/swap.go
- cmd/pvecsictl/utils.go
- docs/deploy/pvc.yaml
- docs/pvecsictl.md
- go.mod
We need to verify all necessary permissions before performing dangerous tasks.
close #249
> fix: check rbac permission

- CHANGELOG.md
- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- docs/deploy/proxmox-csi-plugin-release.yml
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
- go.mod
- go.sum
> chore: release v0.8.0

- .goreleaser.yml
- go.mod
- go.sum
- hack/e2e-tests.md
- pkg/csi/helper.go
- pkg/csi/node.go
Sanitize the output logs.
Add e2e manual test example.
> fix: encrypted volumes logs

- README.md
- docs/faq.md
Add fast answers to common questions
> docs: add faq

- docs/install.md
Example to install CSI and CCM together in Talos machine config.
https://github.com/sergelogvinov/proxmox-csi-plugin/issues/267
> docs: update talos example

- docs/install.md
fixes error: 'Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte'
k8s doesn't allow strings as showed in example
> docs: fix secret in talos example

- README.md
- docs/architecture.md
- docs/eraser.md
Replace pvc/pv migration by animated gif.
> docs: update schema

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- charts/proxmox-csi-plugin/values.yaml
- docs/deploy/proxmox-csi-plugin-release.yml
- docs/deploy/proxmox-csi-plugin-talos.yml
- docs/deploy/proxmox-csi-plugin.yml
- docs/install.md
Update helm chart and install instruction for k0s microk8s.
> docs: k0s microk8s setup

- pkg/csi/controller.go
- pkg/csi/controller_test.go
- pkg/csi/utils.go
- pkg/csi/utils_test.go
Change RoundUpSize function. Nothing changes but it looks better.
Part of #223
> refactor: change round up size

- pkg/csi/controller.go
- pkg/csi/utils.go
We can use only megabyte size chunk.
Api supports G,M values in size param.
#291 
> fix: volume size

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- charts/proxmox-csi-plugin/values.yaml
> chore(chart): update csi sidecar

- .github/workflows/build-edge.yaml
- .github/workflows/build-test.yaml
- .github/workflows/charts.yaml
- .github/workflows/conform.yaml
- .github/workflows/release-charts.yaml
- .github/workflows/release-please.yml
- .github/workflows/release-pre.yaml
- .github/workflows/release.yaml
- .github/workflows/stale.yaml
- docs/release.md
Release please prerelease checks fixes.
Pin build image.
> cicd: gh-actions prerelease checks

- pkg/csi/controller.go
- pkg/csi/controller_test.go
- pkg/tools/nodes.go
> refactor: get vmid by uuid

- README.md
- docs/options.md
Add example of VolumeAttributesClass resource.
close #303
refs #201
> docs: volume attribute class

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- charts/proxmox-csi-plugin/templates/controller-deployment.yaml
- charts/proxmox-csi-plugin/values.yaml
- docker-compose.yml
Upgrate CSI sidecars to support VolumeAttributesClass.
> chore: update sidecars

- docker-compose.yml
- docs/options.md
- docs/proxmox-zfs.yaml
- pkg/csi/controller.go
- pkg/csi/driver.go
- pkg/csi/parameters.go
- pkg/csi/parameters_test.go
- pkg/proxmox/doc.go
- pkg/proxmox/vm.go
- pkg/proxmox/volume.go
Add the capability to replicate a ZFS disk to another zone (proxmox node).
ref #186
> feat: volume replication

- README.md
Add VolumeAttributesClass and ZFS replication to README.md
> docs: update scope project

- README.md
- docs/install.md
- docs/options.md
Describe region/cluster name.
Add example annotation for storage class.
#325 #328
> docs: update docs

- docs/install.md
- docs/options.md
Fix typo stirageclass.kubernetes.io -> storageclass.kubernetes.io
#339
> docs: typo fix

- .conform.yaml
- CONTRIBUTING.md
Describe why a single commit is very important.
> feat: enforce single commit requirement

- .github/workflows/release-pre.yaml
- .github/workflows/release.yaml
- .goreleaser.yml
We did not get the working configuration for release 2.10.
> revert: goreleaser homebrew casks

- README.md
- docs/faq.md
- docs/proxmox-rbd.yaml
- pkg/csi/controller.go
- pkg/csi/controller_test.go
The additional check is skipped if the storage is marked as shared.
> feat: get capacity with shared storages

- .github/workflows/build-edge.yaml
- .github/workflows/build-test.yaml
- .github/workflows/release-charts.yaml
- .github/workflows/release.yaml
- .golangci.yml
- cmd/pvecsictl/swap.go
- pkg/csi/controller.go
- pkg/csi/controller_test.go
- pkg/csi/helper_test.go
- pkg/csi/node.go
- pkg/csi/node_test.go
Switch to golangci-lint version 2.2.2
> chore: upgrade go linter

- docs/options.md
- docs/proxmox-rbd.yaml
- pkg/csi/controller.go
- pkg/csi/driver.go
- pkg/csi/parameters.go
Support raw and qcow2 storage format.
close #396
> feat: qcow2 storage format

- docs/config.md
- docs/install.md
Describe the feature flags of the plugin
> docs: add csi config description

- .conform.yaml
- Makefile
- cmd/pvecsictl/migrate.go
- go.mod
- go.sum
- hack/proxmox-config.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/csi/controller.go
- pkg/csi/controller_test.go
- pkg/proxmoxpool/pool.go
- pkg/proxmoxpool/pool_test.go
- pkg/tools/nodes.go
- pkg/utils/provider/doc.go
- pkg/utils/provider/provider.go
- pkg/utils/provider/provider_test.go
Copy cloud-config module and provider utils.
> refactor: remove ccm dependency

- charts/proxmox-csi-plugin/Chart.yaml
- charts/proxmox-csi-plugin/README.md
- charts/proxmox-csi-plugin/templates/_storage.tpl
It is allowed to set the SSD storageClass parameter to false
https://github.com/sergelogvinov/proxmox-csi-plugin/issues/404
> fix(chart): ssd parameter

- charts/proxmox-csi-plugin/.helmignore
- charts/proxmox-csi-plugin/README.md.gotmpl
- docs/install.md
ZFS replication requires additional permissions.
https://github.com/sergelogvinov/proxmox-csi-plugin/issues/414
> docs: update proxmox permissions
